"""Migration test fixtures originating from exact public v0.1.2 (fb5641c).

The canonical positive fixtures are generated by running the ACTUAL public
v0.1.2 code from a disposable checkout of `fb5641c`. This module locates or
builds such a checkout on demand and generates fixtures deterministically.

Provenance: every fixture is generated by executing the workflow function
source (embedded verbatim) against a fresh worktree at exact commit
`fb5641cc1a3f1f54b96bba3af88ec5a1b010f4e5` (tag `v0.1.2-integrity`). The
generated journal hashes are therefore exact public-code outputs; event_ids
are UUID-random, so tests assert structure/semantics rather than exact
bytes. A `_PROVENANCE.md` is written into each generated fixture root.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Callable

LEGACY_COMMIT = "fb5641cc1a3f1f54b96bba3af88ec5a1b010f4e5"
LEGACY_TAG = "v0.1.2-integrity"

# Location of the canonical dev checkout (used to locate the fb5641c commit).
REPO_ROOT = Path(__file__).resolve().parents[2]

# Per-process checkout + script paths (parallel-runner safe via tempfile).
_FIXTURE_DIR = Path(tempfile.gettempdir()) / f"mf-v012-fixtures-{__import__('os').getpid()}"
_CHECKOUT = Path(tempfile.gettempdir()) / f"mf-v012-fixturegen-{__import__('os').getpid()}"


def _workflow_source(workflow: Callable) -> str:
    """Return the exact source of a workflow function for embedding."""
    import inspect

    return inspect.getsource(workflow)


def _find_fb5641c() -> Path | None:
    """Return the repo if it contains fb5641c, else None."""
    try:
        result = subprocess.run(
            ["git", "-C", str(REPO_ROOT), "cat-file", "-t", LEGACY_COMMIT],
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            return None
    except Exception:  # pragma: no cover
        return None
    return REPO_ROOT


def build_legacy_checkout(dest: Path) -> Path | None:
    """Create a disposable worktree of fb5641c. Returns the checkout root.

    Skips rebuild when the per-process checkout already exists at the exact
    commit (parallel-runner safe; avoids two git subprocesses per fixture).
    """
    repo = _find_fb5641c()
    if repo is None:
        return None
    # Fast path: checkout exists and is at the frozen commit.
    if dest.is_dir():
        probe = subprocess.run(
            ["git", "-C", str(dest), "rev-parse", "HEAD"],
            capture_output=True, text=True,
        )
        if probe.returncode == 0 and probe.stdout.strip() == LEGACY_COMMIT:
            return dest
    # If the path is already a registered worktree, remove it cleanly first.
    subprocess.run(
        ["git", "-C", str(repo), "worktree", "remove", "--force", str(dest)],
        capture_output=True,
        text=True,
    )
    if dest.exists():
        shutil.rmtree(dest, ignore_errors=True)
    result = subprocess.run(
        ["git", "-C", str(repo), "worktree", "add", "--detach", str(dest), LEGACY_COMMIT],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        return None
    return dest


def generate_fixture(
    root: Path,
    *,
    workflow: Callable,
) -> Path:
    """Generate a v0.1.2 fixture at `root` using the public code.

    `workflow(engine, root)` drives the scenario; returns nothing. The
    workflow function source is embedded into the generated script verbatim
    (public-era code running against the fb5641c checkout).
    """
    root = Path(root)
    if not build_legacy_checkout(_CHECKOUT):
        raise RuntimeError(
            "cannot build fb5641c checkout; fixture generation requires the "
            "exact public code"
        )

    code = f"""
import json, sys
sys.path.insert(0, {str(_CHECKOUT)!r})
from pathlib import Path
from core.manifest.store import ManifestStore
from core.adapters.artifact_store import ArtifactStore
from core.engine import PipelineEngine

root = Path({str(root)!r})
import shutil; shutil.rmtree(root, ignore_errors=True)
root.mkdir(parents=True, exist_ok=True)
store = ManifestStore(root)
engine = PipelineEngine(store, ArtifactStore(root / "artifacts"))

# workflow source (exact public-era code running against fb5641c)
{_workflow_source(workflow)}

{workflow.__name__}(engine, root)
"""
    _FIXTURE_DIR.mkdir(parents=True, exist_ok=True)
    script = _FIXTURE_DIR / "gen-script.py"
    script.write_text(code, encoding="utf-8")
    py = sys.executable
    subprocess.run([py, str(script)], check=True, capture_output=True)
    # Provenance record inside the fixture.
    (root / "_PROVENANCE.md").write_text(
        "Generated by executing the workflow against public v0.1.2 code at\n"
        f"commit {LEGACY_COMMIT} (tag {LEGACY_TAG}), checkout {_CHECKOUT}.\n"
        f"Workflow: {workflow.__name__}\n",
        encoding="utf-8",
    )
    return root


def standard_workflow(engine, root: Path) -> None:
    """Full valid v0.1.2 workflow: input -> objective -> summary -> confirm
    -> artifact -> cancel."""
    import datetime

    class Clock:
        def __init__(self, start: str = "2026-08-07T00:00:00+00:00") -> None:
            self.t = datetime.datetime.fromisoformat(start)
            self._delta = datetime.timedelta(minutes=1)

        def __call__(self) -> str:
            s = self.t.isoformat()
            self.t += self._delta
            return s

    clock = Clock()
    engine._now = clock  # override the engine clock deterministically

    def apply(envdict):
        return engine.apply_json(json.dumps(envdict))

    engine.create_package("pkg_demo_001", "Build a skill")
    apply({
        "protocol_version": "0.1", "action_id": "act_in_1",
        "package_id": "pkg_demo_001", "expected_revision": 0,
        "action": "record_input", "basis": {},
        "payload": {"input_id": "in_1", "kind": "text", "content": "hello",
                    "source": "operator", "disposition": "incorporated"},
    })
    apply({
        "protocol_version": "0.1", "action_id": "act_obj_1",
        "package_id": "pkg_demo_001", "expected_revision": 1,
        "action": "set_objective", "basis": {},
        "payload": {"statement": "Build a skill", "desired_outcomes": ["ship it"]},
    })
    m2 = apply({
        "protocol_version": "0.1", "action_id": "act_prep_1",
        "package_id": "pkg_demo_001", "expected_revision": 2,
        "action": "prepare_summary", "basis": {}, "payload": {},
    })
    apply({
        "protocol_version": "0.1", "action_id": "act_conf_1",
        "package_id": "pkg_demo_001", "expected_revision": 3,
        "action": "confirm_summary",
        "basis": {"summary_sha256": m2.manifest["summary"]["canonical_sha256"]},
        "payload": {"operator_id": "vincent"},
    })
    apply({
        "protocol_version": "0.1", "action_id": "act_art_1",
        "package_id": "pkg_demo_001", "expected_revision": 4,
        "action": "record_draft_artifact", "basis": {},
        "payload": {"artifact_id": "art_1", "kind": "skill",
                    "logical_path": "skills/x/SKILL.md", "content": "body"},
    })
    apply({
        "protocol_version": "0.1", "action_id": "act_cancel_1",
        "package_id": "pkg_demo_001", "expected_revision": 5,
        "action": "cancel", "basis": {}, "payload": {},
    })


def non_ascii_workflow(engine, root: Path) -> None:
    """Workflow with non-ASCII semantic content (ensure_ascii divergence)."""
    import datetime

    class Clock:
        def __init__(self, start: str = "2026-08-07T00:00:00+00:00") -> None:
            self.t = datetime.datetime.fromisoformat(start)
            self._delta = datetime.timedelta(minutes=1)

        def __call__(self) -> str:
            s = self.t.isoformat()
            self.t += self._delta
            return s

    engine._now = Clock()

    def apply(envdict):
        return engine.apply_json(json.dumps(envdict))

    engine.create_package("pkg_unicode_001", "สร้างทักษะ – 日本語で")
    apply({
        "protocol_version": "0.1", "action_id": "act_in_1",
        "package_id": "pkg_unicode_001", "expected_revision": 0,
        "action": "record_input", "basis": {},
        "payload": {"input_id": "in_1", "kind": "text", "content": "สวัสดี こんにちは",
                    "source": "operator", "disposition": "incorporated"},
    })
    apply({
        "protocol_version": "0.1", "action_id": "act_obj_1",
        "package_id": "pkg_unicode_001", "expected_revision": 1,
        "action": "set_objective", "basis": {},
        "payload": {"statement": "เป้าหมาย 目標", "desired_outcomes": ["ส่งมอบ", "納品"]},
    })


def optional_omitted_workflow(engine, root: Path) -> None:
    """Workflow exercising omitted-vs-explicit optional fields:
    record_input without exclusion_reason; set_objective without
    desired_outcomes; confirm_summary with default operator."""
    import datetime

    class Clock:
        def __init__(self, start: str = "2026-08-07T00:00:00+00:00") -> None:
            self.t = datetime.datetime.fromisoformat(start)
            self._delta = datetime.timedelta(minutes=1)

        def __call__(self) -> str:
            s = self.t.isoformat()
            self.t += self._delta
            return s

    engine._now = Clock()

    def apply(envdict):
        return engine.apply_json(json.dumps(envdict))

    engine.create_package("pkg_opt_001", "optional fields")
    # record_input WITHOUT exclusion_reason (omitted)
    apply({
        "protocol_version": "0.1", "action_id": "act_in_1",
        "package_id": "pkg_opt_001", "expected_revision": 0,
        "action": "record_input", "basis": {},
        "payload": {"input_id": "in_1", "kind": "text", "content": "hello",
                    "source": "operator", "disposition": "incorporated"},
    })
    # set_objective WITHOUT desired_outcomes (omitted)
    apply({
        "protocol_version": "0.1", "action_id": "act_obj_1",
        "package_id": "pkg_opt_001", "expected_revision": 1,
        "action": "set_objective", "basis": {},
        "payload": {"statement": "Only statement"},
    })
    m2 = apply({
        "protocol_version": "0.1", "action_id": "act_prep_1",
        "package_id": "pkg_opt_001", "expected_revision": 2,
        "action": "prepare_summary", "basis": {}, "payload": {},
    })
    # confirm_summary WITHOUT operator_id (default "operator")
    apply({
        "protocol_version": "0.1", "action_id": "act_conf_1",
        "package_id": "pkg_opt_001", "expected_revision": 3,
        "action": "confirm_summary",
        "basis": {"summary_sha256": m2.manifest["summary"]["canonical_sha256"]},
        "payload": {},
    })
    # cancel WITHOUT reason (omitted)
    apply({
        "protocol_version": "0.1", "action_id": "act_cancel_1",
        "package_id": "pkg_opt_001", "expected_revision": 4,
        "action": "cancel", "basis": {}, "payload": {},
    })


def cancel_arbitrary_reason_workflow(engine, root: Path) -> None:
    """Cancel with an arbitrary non-empty reason (not reconstructable)."""
    import datetime

    class Clock:
        def __init__(self, start: str = "2026-08-07T00:00:00+00:00") -> None:
            self.t = datetime.datetime.fromisoformat(start)
            self._delta = datetime.timedelta(minutes=1)

        def __call__(self) -> str:
            s = self.t.isoformat()
            self.t += self._delta
            return s

    engine._now = Clock()

    def apply(envdict):
        return engine.apply_json(json.dumps(envdict))

    engine.create_package("pkg_cancel_001", "cancel with reason")
    apply({
        "protocol_version": "0.1", "action_id": "act_in_1",
        "package_id": "pkg_cancel_001", "expected_revision": 0,
        "action": "record_input", "basis": {},
        "payload": {"input_id": "in_1", "kind": "text", "content": "hello",
                    "source": "operator", "disposition": "incorporated"},
    })
    apply({
        "protocol_version": "0.1", "action_id": "act_cancel_1",
        "package_id": "pkg_cancel_001", "expected_revision": 1,
        "action": "cancel", "basis": {},
        "payload": {"reason": "operator decided to abandon this work"},
    })


def revise_intake_workflow(engine, root: Path) -> None:
    """Workflow exercising revise_intake (summary invalidated)."""
    import datetime

    class Clock:
        def __init__(self, start: str = "2026-08-07T00:00:00+00:00") -> None:
            self.t = datetime.datetime.fromisoformat(start)
            self._delta = datetime.timedelta(minutes=1)

        def __call__(self) -> str:
            s = self.t.isoformat()
            self.t += self._delta
            return s

    engine._now = Clock()

    def apply(envdict):
        return engine.apply_json(json.dumps(envdict))

    engine.create_package("pkg_revise_001", "revise intake")
    apply({
        "protocol_version": "0.1", "action_id": "act_in_1",
        "package_id": "pkg_revise_001", "expected_revision": 0,
        "action": "record_input", "basis": {},
        "payload": {"input_id": "in_1", "kind": "text", "content": "hello",
                    "source": "operator", "disposition": "incorporated"},
    })
    apply({
        "protocol_version": "0.1", "action_id": "act_obj_1",
        "package_id": "pkg_revise_001", "expected_revision": 1,
        "action": "set_objective", "basis": {},
        "payload": {"statement": "Build a skill"},
    })
    apply({
        "protocol_version": "0.1", "action_id": "act_prep_1",
        "package_id": "pkg_revise_001", "expected_revision": 2,
        "action": "prepare_summary", "basis": {}, "payload": {},
    })
    apply({
        "protocol_version": "0.1", "action_id": "act_revise_1",
        "package_id": "pkg_revise_001", "expected_revision": 3,
        "action": "revise_intake", "basis": {}, "payload": {},
    })


def all_action_families_workflow(engine, root: Path) -> None:
    """Every action family in one package: input, objective, summary, confirm,
    revise, artifact, cancel."""
    import datetime

    class Clock:
        def __init__(self, start: str = "2026-08-07T00:00:00+00:00") -> None:
            self.t = datetime.datetime.fromisoformat(start)
            self._delta = datetime.timedelta(minutes=1)

        def __call__(self) -> str:
            s = self.t.isoformat()
            self.t += self._delta
            return s

    engine._now = Clock()

    def apply(envdict):
        return engine.apply_json(json.dumps(envdict))

    engine.create_package("pkg_all_001", "all action families")
    apply({
        "protocol_version": "0.1", "action_id": "act_in_1",
        "package_id": "pkg_all_001", "expected_revision": 0,
        "action": "record_input", "basis": {},
        "payload": {"input_id": "in_1", "kind": "text", "content": "hello",
                    "source": "operator", "disposition": "incorporated",
                    "exclusion_reason": None},
    })
    apply({
        "protocol_version": "0.1", "action_id": "act_obj_1",
        "package_id": "pkg_all_001", "expected_revision": 1,
        "action": "set_objective", "basis": {},
        "payload": {"statement": "Build a skill", "desired_outcomes": ["ship it"]},
    })
    m2 = apply({
        "protocol_version": "0.1", "action_id": "act_prep_1",
        "package_id": "pkg_all_001", "expected_revision": 2,
        "action": "prepare_summary", "basis": {}, "payload": {},
    })
    apply({
        "protocol_version": "0.1", "action_id": "act_conf_1",
        "package_id": "pkg_all_001", "expected_revision": 3,
        "action": "confirm_summary",
        "basis": {"summary_sha256": m2.manifest["summary"]["canonical_sha256"]},
        "payload": {"operator_id": "vincent"},
    })
    apply({
        "protocol_version": "0.1", "action_id": "act_revise_1",
        "package_id": "pkg_all_001", "expected_revision": 4,
        "action": "revise_intake", "basis": {}, "payload": {},
    })
    # After revise: intake again; record another input (exclusion_reason),
    # objective, summary, confirm, then artifact (legal in AUTHORING_AUTHORIZED).
    apply({
        "protocol_version": "0.1", "action_id": "act_in_2",
        "package_id": "pkg_all_001", "expected_revision": 5,
        "action": "record_input", "basis": {},
        "payload": {"input_id": "in_2", "kind": "text", "content": "world",
                    "source": "operator", "disposition": "excluded",
                    "exclusion_reason": "duplicate"},
    })
    apply({
        "protocol_version": "0.1", "action_id": "act_obj_2",
        "package_id": "pkg_all_001", "expected_revision": 6,
        "action": "set_objective", "basis": {},
        "payload": {"statement": "Build a skill", "desired_outcomes": ["ship it"]},
    })
    m3 = apply({
        "protocol_version": "0.1", "action_id": "act_prep_2",
        "package_id": "pkg_all_001", "expected_revision": 7,
        "action": "prepare_summary", "basis": {}, "payload": {},
    })
    apply({
        "protocol_version": "0.1", "action_id": "act_conf_2",
        "package_id": "pkg_all_001", "expected_revision": 8,
        "action": "confirm_summary",
        "basis": {"summary_sha256": m3.manifest["summary"]["canonical_sha256"]},
        "payload": {"operator_id": "vincent"},
    })
    apply({
        "protocol_version": "0.1", "action_id": "act_art_1",
        "package_id": "pkg_all_001", "expected_revision": 9,
        "action": "record_draft_artifact", "basis": {},
        "payload": {"artifact_id": "art_1", "kind": "skill",
                    "logical_path": "skills/x/SKILL.md", "content": "body"},
    })
    apply({
        "protocol_version": "0.1", "action_id": "act_cancel_1",
        "package_id": "pkg_all_001", "expected_revision": 10,
        "action": "cancel", "basis": {}, "payload": {},
    })


def overlimit_intent_workflow(engine, root: Path) -> None:
    """Intent exceeding the CURRENT MAX_INTENT_CHARS (public-v0.1.2-valid,
    current-invalid under the frozen compatibility matrix)."""
    import datetime

    class Clock:
        def __init__(self, start: str = "2026-08-07T00:00:00+00:00") -> None:
            self.t = datetime.datetime.fromisoformat(start)
            self._delta = datetime.timedelta(minutes=1)

        def __call__(self) -> str:
            s = self.t.isoformat()
            self.t += self._delta
            return s

    engine._now = Clock()

    def apply(envdict):
        return engine.apply_json(json.dumps(envdict))

    # 70_000 chars: > current 65_536 intent limit; legacy had no intent limit.
    big = "x" * 70_000
    engine.create_package("pkg_bigintent_001", big)
    apply({
        "protocol_version": "0.1", "action_id": "act_in_1",
        "package_id": "pkg_bigintent_001", "expected_revision": 0,
        "action": "record_input", "basis": {},
        "payload": {"input_id": "in_1", "kind": "text", "content": "hello",
                    "source": "operator", "disposition": "incorporated"},
    })


def overlimit_input_workflow(engine, root: Path) -> None:
    """Input content exceeding the CURRENT MAX_CONTENT_CHARS (legacy-valid)."""
    import datetime

    class Clock:
        def __init__(self, start: str = "2026-08-07T00:00:00+00:00") -> None:
            self.t = datetime.datetime.fromisoformat(start)
            self._delta = datetime.timedelta(minutes=1)

        def __call__(self) -> str:
            s = self.t.isoformat()
            self.t += self._delta
            return s

    engine._now = Clock()

    def apply(envdict):
        return engine.apply_json(json.dumps(envdict))

    engine.create_package("pkg_biginput_001", "big input")
    big = "y" * (1_048_576 + 5)
    apply({
        "protocol_version": "0.1", "action_id": "act_in_1",
        "package_id": "pkg_biginput_001", "expected_revision": 0,
        "action": "record_input", "basis": {},
        "payload": {"input_id": "in_1", "kind": "text", "content": big,
                    "source": "operator", "disposition": "incorporated"},
    })


def current_invalid_identifier_workflow(engine, root: Path) -> None:
    """input_id that is public-v0.1.2-valid but current-invalid (space)."""
    import datetime

    class Clock:
        def __init__(self, start: str = "2026-08-07T00:00:00+00:00") -> None:
            self.t = datetime.datetime.fromisoformat(start)
            self._delta = datetime.timedelta(minutes=1)

        def __call__(self) -> str:
            s = self.t.isoformat()
            self.t += self._delta
            return s

    engine._now = Clock()

    def apply(envdict):
        return engine.apply_json(json.dumps(envdict))

    engine.create_package("pkg_badid_001", "bad identifier")
    apply({
        "protocol_version": "0.1", "action_id": "act_in_1",
        "package_id": "pkg_badid_001", "expected_revision": 0,
        "action": "record_input", "basis": {},
        "payload": {"input_id": "in 1", "kind": "text", "content": "hello",
                    "source": "operator", "disposition": "incorporated"},
    })


def invalid_logical_path_workflow(engine, root: Path) -> None:
    """Artifact logical_path that is public-v0.1.2-valid but
    current-invalid (absolute path)."""
    import datetime

    class Clock:
        def __init__(self, start: str = "2026-08-07T00:00:00+00:00") -> None:
            self.t = datetime.datetime.fromisoformat(start)
            self._delta = datetime.timedelta(minutes=1)

        def __call__(self) -> str:
            s = self.t.isoformat()
            self.t += self._delta
            return s

    engine._now = Clock()

    def apply(envdict):
        return engine.apply_json(json.dumps(envdict))

    engine.create_package("pkg_badpath_001", "bad logical path")
    apply({
        "protocol_version": "0.1", "action_id": "act_in_1",
        "package_id": "pkg_badpath_001", "expected_revision": 0,
        "action": "record_input", "basis": {},
        "payload": {"input_id": "in_1", "kind": "text", "content": "hello",
                    "source": "operator", "disposition": "incorporated"},
    })
    apply({
        "protocol_version": "0.1", "action_id": "act_obj_1",
        "package_id": "pkg_badpath_001", "expected_revision": 1,
        "action": "set_objective", "basis": {},
        "payload": {"statement": "Build a skill"},
    })
    m2 = apply({
        "protocol_version": "0.1", "action_id": "act_prep_1",
        "package_id": "pkg_badpath_001", "expected_revision": 2,
        "action": "prepare_summary", "basis": {}, "payload": {},
    })
    apply({
        "protocol_version": "0.1", "action_id": "act_conf_1",
        "package_id": "pkg_badpath_001", "expected_revision": 3,
        "action": "confirm_summary",
        "basis": {"summary_sha256": m2.manifest["summary"]["canonical_sha256"]},
        "payload": {"operator_id": "vincent"},
    })
    apply({
        "protocol_version": "0.1", "action_id": "act_art_1",
        "package_id": "pkg_badpath_001", "expected_revision": 4,
        "action": "record_draft_artifact", "basis": {},
        "payload": {"artifact_id": "art_1", "kind": "skill",
                    "logical_path": "/etc/passwd", "content": "body"},
    })


def control_char_identifier_workflow(engine, root: Path) -> None:
    """input_id containing a control character (public-valid,
    current-invalid under the compatibility matrix)."""
    import datetime

    class Clock:
        def __init__(self, start: str = "2026-08-07T00:00:00+00:00") -> None:
            self.t = datetime.datetime.fromisoformat(start)
            self._delta = datetime.timedelta(minutes=1)

        def __call__(self) -> str:
            s = self.t.isoformat()
            self.t += self._delta
            return s

    engine._now = Clock()

    def apply(envdict):
        return engine.apply_json(json.dumps(envdict))

    engine.create_package("pkg_ctrlchar_001", "control char identifier")
    apply({
        "protocol_version": "0.1", "action_id": "act_in_1",
        "package_id": "pkg_ctrlchar_001", "expected_revision": 0,
        "action": "record_input", "basis": {},
        "payload": {"input_id": "in\x01", "kind": "text", "content": "hello",
                    "source": "operator", "disposition": "incorporated"},
    })
